name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: '0 0 * * 0'
  workflow_dispatch:

jobs:
  ci:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - ubi8
        - ubi9
    steps:
    - uses: actions/checkout@v4
    - name: Build docker image
      run: rake docker_images[${{ matrix.platform }}]
    - name: Run tests
      run: rake docker_test[${{ matrix.platform }}]
